# PEiAR - Laboratorium 2
## FAKTOR c.d. (= typ czynnikowy / kategoryczny / wyliczeniowy)
### Zad. 1
Zapytano 20 ludzi o markę samochodu.
`cars = c('VW', 'Toyota', 'Renault', 'VW', 'Audi', 'Citroen', 'Fiat', 'Mazda', 'Toyota',
'Renault','Renault', 'Audi', 'VW', 'VW', 'Audi', 'Mazda', 'Skoda', 'VW', 'Skoda')`.
Zwróć zestaw danych cars wraz z unikatowymi jego wartościami
// factor( ... )
Zwróć same wartości unikatowe
// levels(factor( ... ))
Zwróć zestawienie wartości unikatowych wraz z ich wagami
// table(factor( ... ))


In [25]:
cars <- c('VW', 'Toyota', 'Renault', 'VW', 'Audi', 'Citroen', 'Fiat', 'Mazda', 'Toyota',
'Renault','Renault', 'Audi', 'VW', 'VW', 'Audi', 'Mazda', 'Skoda', 'VW', 'Skoda', 'Renault')
factor(cars)
levels(factor(cars))
table(factor(cars))

[1] VW      Toyota  Renault VW      Audi    Citroen Fiat    Mazda   Toyota 
[10] Renault Renault Audi    VW      VW      Audi    Mazda   Skoda   VW     
[19] Skoda   Renault
Levels: Audi Citroen Fiat Mazda Renault Skoda Toyota VW

[1] "Audi"    "Citroen" "Fiat"    "Mazda"   "Renault" "Skoda"   "Toyota" 
[8] "VW"


   Audi Citroen    Fiat   Mazda Renault   Skoda  Toyota      VW 
      3       1       1       2       4       2       2       5 

### Zad.2
Dziesięciu osobom zadano po dwa pytania, na które mogli odpowiedzieć tak('T’), nie ('N’) lub nie
wiem ('X’).
i) Wygeneruj przykładowy wektor a_ z 10 odpowiedziami na I pytanie i przykładowy wektor b_ z
odpowiedziami na pytanie II.
ii) Zestaw te dane używając funkcji table().
iii) Ile było osób które na oba pytania odpowiedziały ‘nie wiem’, ile osób odpowiedziało na I ‘nie’ a
na drugie ‘tak’?


In [10]:
a_ <- sample(c('T', 'N', 'X'), 10, T)
b_ <- sample(c('T', 'N', 'X'), 10, T)
table(a_, b_)

   b_
a_  N T X
  N 1 0 1
  T 3 1 1
  X 0 1 2

### Zad.3
Osoby z poprzedniego zadania zapytano o wiek. Wygeneruj przykładowy wektor odpowiedzi age_
Używając funkcji tapply(..vector1., ..correlated vector2.., ..function applied for vector1..)
//‘apply for table’//
znajdź:
i) średnią wieku tych, którzy na I pytanie odpowiedzieli ‘tak’
ii) odchylenie standardowe wieku osób które na II pytanie odpowiedziały ‘nie’


In [14]:
age_ <- sample(5:100, 10, T)
tapply(age_, a_, mean)
tapply(age_, a_, sd)

N    T    X 
54.5 69.6 53.0

N        T        X 
33.23402 34.91132 36.38681

### Zad.4
Pozostając w kontekście zad.1, użyj funkcji cut(..data vector.., vector of intervals edges..) aby
wygenerować wektor (a właściwie faktor) ageIntervals_ przedziałów: (0, 20], (20, 30], (30, 50] i
(50, 75] odpowiadających wiekowi poszczególnych respondentów.
Przy użyciu funkcji table(...) wygeneruj zestawienie ilustrujące ile osób - w poszczególnych
przedziałach wiekowych - udzielało odpowiedzi.


In [26]:
age_ <- sample(5:75, 20, T)
ageIntervals_ <- cut(age_, c(0, 20, 30, 50, 75))
ageIntervals_
table(factor(cars), ageIntervals_)

[1] (20,30] (50,75] (30,50] (50,75] (30,50] (0,20]  (30,50] (50,75] (20,30]
[10] (30,50] (0,20]  (20,30] (30,50] (0,20]  (0,20]  (50,75] (50,75] (20,30]
[19] (0,20]  (30,50]
Levels: (0,20] (20,30] (30,50] (50,75]

         ageIntervals_
          (0,20] (20,30] (30,50] (50,75]
  Audi         1       1       1       0
  Citroen      1       0       0       0
  Fiat         0       0       1       0
  Mazda        0       0       0       2
  Renault      1       0       3       0
  Skoda        1       0       0       1
  Toyota       0       1       0       1
  VW           1       2       1       1

## MACIERZ (= typ tablicowy)
### Zad.5
Wygeneruj wektor x_ kolejnych liczb naturalnych od 12 do 41. Używając funkcji dim(..vector..)
wygeneruj z wektora x_ macierz o wymiarach 3x10, potem zmień jej wymiary na 5x6, w końcu
10x3.
Zwróć siódmą współrzędną wektora. Następnie zwróć komórkę z szóstego wiersza i drugiej
kolumny. Zwróć dane z trzeciej kolumny macierzy. Zwróć piąty wiersz macierzy.
Przy użyciu polecenia dim(), wyświetl aktualne wymiary macierzy.


In [41]:
x_ <- 12:41
dim(x_) <- c(3,10)
dim(x_) <- c(5, 6)
dim(x_) <- c(10, 3)
x_
x_[7]
x_[6, 2]
x_[, 3]
x_[5,]
dim(x_)

[,1] [,2] [,3]
 [1,] 12   22   32  
 [2,] 13   23   33  
 [3,] 14   24   34  
 [4,] 15   25   35  
 [5,] 16   26   36  
 [6,] 17   27   37  
 [7,] 18   28   38  
 [8,] 19   29   39  
 [9,] 20   30   40  
[10,] 21   31   41

[1] 18

[1] 27

[1] 32 33 34 35 36 37 38 39 40 41

[1] 16 26 36

[1] 10  3

### Zad.6
Powróć w macierzy x_ (zad.5) do wymiarów 5x6. Chcemy móc operować jednocześnie na jej
komórkach o adresach: [1,2], [1,6], [4,3], [4,5], [5,1], [5,2]. W tym celu, używając:
i) poznanego wcześniej sposobu generowania macierzy (z zadanego wektora)
ii) funkcji array(..data vector.., dim = c(..., …))
wygeneruj najpierw macierz y_ o wymiarach 6x2, która w kolejnych wierszach ma współrzędne
każdego z w/w punktów.
Następnie wyświetl dane z tablicy x_ o adresach jw. Nadpisz te dane tak by miały wartość 0 i
wywołaj nadpisaną tablicę x_.


In [42]:
dim(x_) <- c(5, 6)
y_ <- array(x_, dim = c(6, 2))

### Zad.7
Wygeneruj wektor a_ kolejnych liczb naturalnych od 1 do 12 i utwórz macierz trójwymiarową o
wymiarach 3x2x2. Wywołaj ją i zinterpretuj wynik.


In [47]:
a_ <- 1:12
dim(a_) <- c(3, 2, 2)
a_

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

## OPERACJA NA TABLICACH
### Zad.8
Używając funkcji
outer(..vertical data vector.., horizontal data vector.., ‘operation’ //multiplication by default//)
wygeneruj:
i) tabliczkę mnożenia (dla liczb od 1 do 10)
ii) tabliczkę dzielenia
iii) tabliczkę reszt z dzielenia
iv) tabliczkę części całkowitych z dzielenia.


### Zad.9
Przy użyciu funkcji array(), wygeneruj dowolną macierz dwuwymiarową i przy użyciu funkcji
aperm(..matrix..) //permutującej wymiary macierzy//
dokonaj transpozycji macierzy. Jak inaczej uzyskać transpozycję macierzy?


### Zad.10
Wygeneruj 3 wektory a, b i c o równej długości. Przy użyciu funkcji
rbind(..row1.., ..row2, ...) oraz cbind(..column1.., ..column2..)
wygeneruj z nich:
i) macierz o zadanych wierszach
ii) macierz o zadanych kolumnach.
Używając funkcji as.vector(...matrix...) zrób z otrzymanej macierzy wektor o współrzędnych z
kolejnych kolumn.


### Zad.11
Wygeneruj dwie macierze: m_1 o wymiarach 3x2 i m_2 o wymiarach 2x4. Przemnóż je przez siebie
używając operatora %*% mnożenia macierzy. Sprawdź pisemnie uzyskany wynik.


### Zad.12
Przy użyciu funkcji solve(...) znajdź macierz odwrotną do macierzy m = rbind(c(3, 1), c(1, 1)). Jak
sprawdzić poprawność otrzymanego wyniku?


### Zad.13
Rozwiąż układ równań: 3x – 2y + z = 1; x - z = 4; 2y + 2z = 7.


## LISTA (= uporządkowany zbiór elementów różnego typu)
### Zad.14
Utwórz kilka różnych typów danych, np. wektor liczbowy a= [1, pi, 4], wektor wartości logicznych
b =[TRUE, FALSE, FALSE, FALSE], faktor c z danymi: 7, pi, ‘hello’, ‘world’, pi, 6, ‘hello’ oraz
macierz d o dowolnych wymiarach…
Przy użyciu funkcji list(..first data portion, second data portion, ..., last data portion), utwórz listę
zawierającą powyższe porcje z danymi. Zwróć drugi element listy, zwróć zawartość drugiego
elementu listy.


### Zad.15
Utwórz listę z następujących danych: wektora v =[1, 2, 3], zmiennej u=2 oraz macierzy m o
wymiarach3x4 z wartościami: 1 : 12 (pierwsza kolumna: 1, 2, 3, 4, druga: 5, 6, 7, 8 itd...). Wywołaj
listę, po czym łańcuchując nazwy coraz głębszych elementów przy użyciu znaku $, wywołaj tylko
wektor v, potem drugą współrzędną wektora v, potem elementy z pierwszego wiersza tablicy m.